feat: dev에 무중단 배포 적용

diff --git a/jenkins/backend-dev.jenkinsfile b/jenkins/backend-dev.jenkinsfile
--- a/jenkins/backend-dev.jenkinsfile
+++ b/jenkins/backend-dev.jenkinsfile
@@ -36,8 +36,47 @@ pipeline {
             steps {
                 dir('backend/build/libs') {
                     sshagent(credentials: ['key-dallog']) {
-                        sh "scp -o StrictHostKeyChecking=no backend-0.0.1-SNAPSHOT.jar ubuntu@${env.BACKEND_DEV_IP}:/home/ubuntu"
-                        sh "ssh -o StrictHostKeyChecking=no ubuntu@${env.BACKEND_DEV_IP} 'sh run.sh' &"
+                        sh'''
+                        if curl -s "http://15.165.125.109:${env.BLUE_PORT}" > /dev/null
+                        then
+                            target_port=${env.GREEN_PORT}
+                        else
+                            target_port=${env.BLUE_PORT}
+                        fi
+
+                        scp -o StrictHostKeyChecking=no backend-0.0.1-SNAPSHOT.jar ubuntu@${env.BACKEND_DEV_IP}:/home/ubuntu
+                        ssh ubuntu@${env.BACKEND_DEV_IP} 'sh run.sh ${target_port}' &
+
+                        for retry_count in $($seq 10)
+                        do
+                            if curl -s "http://15.165.125.109:${target_port}" > /dev/null
+                            then
+                                echo "Health check success ✅ port number: ${target_port}"
+                                break
+                            fi
+
+                            if [ $retry_count -eq 10 ]
+                            then
+                                echo "Health check failed ❌ port number: ${target_port}"
+                                exit 1
+                            fi
+
+                            echo "The server is not alive yet. Retry health check in 20 seconds... retry count: ${retry_count}"
+                            sleep 20
+                        done
+
+                        ssh ubuntu@${env.BACKEND_DEV_IP} "echo 'set \\\$service_port ${target_port};’ > /etc/nginx/conf.d/service-port.inc && service nginx reload”
+                        echo "Switch the reverse proxy direction of nginx to ${target_port} 🔄"
+
+                        if [ "${target_port}" == "${env.BLUE_PORT}" ]
+                        then
+                            ssh ubuntu@${env.BACKEND_DEV_IP} "fuser -s -k ${env.GREEN_PORT}/tcp"
+                        else
+                            ssh ubuntu@${env.BACKEND_DEV_IP} "fuser -s -k ${env.BLUE_PORT}/tcp"
+                        fi
+
+                        echo "Kill the process on the opposite server. 🔪"
+                        '''
                     }
                 }
             }
